Blog.Web/Models/ViewModels/NotificationViewModel.cs
namespace Blog.Web.Models.ViewModels
{
    public class NotificationViewModel
    {
        public int Id { get; set; }
        public string NotificationMessage { get; set; }
    }
}

Blog.Web/Controllers/AdminBlogPostsController.cs
using Blog.Web.Models.Domain;
using Blog.Web.Models.ViewModels;
using Blog.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.InteropServices;

namespace Blog.Web.Controllers
{
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        public AdminBlogPostsController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }

        

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.DisplayName, Value = x.Id.ToString()})
            };
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {

            var blogpost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,

            };
            var selectedTags = new List<Tag>();

            foreach (var selectedTagId in addBlogPostRequest.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                      selectedTags.Add(existingTag);
                }
            }

            blogpost.Tags = selectedTags;

            await blogPostRepository.AddAsync(blogpost);
			TempData["Success"] = "A new Blog is added!";
			return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {

            var blogpost = await blogPostRepository.GetAllAsync();

            return View(blogpost);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            //retrieve data
          var blogPost = await  blogPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if (tagsDomainModel != null)
            {
                var model = new EditBlogPostRequest
                {
                    Id = blogPost.Id,
                    Heading = blogPost.Heading,
                    PageTitle = blogPost.PageTitle,
                    Content = blogPost.Content,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    UrlHandle = blogPost.UrlHandle,
                    ShortDescription = blogPost.ShortDescription,
                    PublishedDate = blogPost.PublishedDate,
                    Visible = blogPost.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                    }),
                    
                    SelectedTags = blogPost.Tags.Select(x => x.Id.ToString()).ToArray()

					

				};
                

				return View(model);

            }

            //map domain


            

           return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            //map view model back to domain model
            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                PublishedDate = editBlogPostRequest.PublishedDate,
                UrlHandle = editBlogPostRequest.UrlHandle,
                Visible = editBlogPostRequest.Visible,
            };
            //maps tag in domain model

            var selectedTags = new List<Tag>();
            foreach (var selectedTag in editBlogPostRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);
                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            blogPostDomainModel.Tags = selectedTags;
            //submit information to respositry to update
           var updatedBlog = await blogPostRepository.UpdateAsync(blogPostDomainModel);
            if (updatedBlog != null)
            {
				//show success notification
				TempData["Success"] = "Blog is Updated!";
				return RedirectToAction("Edit");
            }
			//show error notification
			TempData["Error"] = "Something went wrong!";
			return RedirectToAction("Edit");

            //redirect to GET
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            //Talk to respo to delete
           var deletedBlogPost = await blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if (deletedBlogPost != null)
            {
				//show success notification
				TempData["Success"] = "Blog is Deleted!";
				return RedirectToAction("List");
            }
			//show erroe noti
			TempData["Error"] = "Something went wrong!";
			return RedirectToAction("Edit" ,new {id = editBlogPostRequest.Id});

           


        }
    }
}

Blog.Web/Controllers/AdminTagsController.cs
using Blog.Web.Data;
using Blog.Web.Models.Domain;
using Blog.Web.Models.ViewModels;
using Blog.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Blog.Web.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository tagRepository;

        public AdminTagsController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }


        [Authorize]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task< IActionResult> Add(AddTagRequest addTagRequest)
        {
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };

            await tagRepository.AddAsync(tag);

            TempData["Success"] = "New Tag is added!";
            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            var tags = await tagRepository.GetAllAsync();

            return View(tags);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
         var tag = await tagRepository.GetAsync(id);

            if (tag != null) 
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };
                return View(editTagRequest);
            }

            return View(null);
        }
        [HttpPost]
        public async Task<IActionResult> Edit (EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

           var updatedTag = await tagRepository.UpdateAsync(tag);

            if (updatedTag != null)
            {
                //show success notification
                TempData["Success"] = "Tag is Edited!";
            }
            else
            {
                //show error notification
                TempData["Error"] = "Somwthing went wrong!";
            }
        
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
         var deletedTag = await tagRepository.DeleteAsync(editTagRequest.Id);
            

            if (deletedTag != null)
            {
                //show success notification
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editTagRequest });
        }

    }
}

Blog.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/Blog.Web.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blog.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>



                        @if (signInManager.IsSignedIn(User) && User.Identity.Name == "admin@bloggie.com")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminTags"
                                       asp-action="Add">
                                            Add Tag
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminTags"
                                       asp-action="List">
                                            Show All Tags
                                        </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminBlogPosts"
                                       asp-action="Add">
                                            Add Blog Post
                                        </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="AdminBlogPosts"
                                       asp-action="List">
                                            All Blog Post
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            
                        }






                    </ul>

                    <div class="d-flex align-items-center">

                        @if (signInManager.IsSignedIn(User))
                        {
                            <div class="me-3 text-light">
                                <p>Welcome, @User?.Identity?.Name</p>
                                </div>

                            <a class="btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Logout">Logout</a>

                        }
                        else
                        {
                            <a class="btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Login">Login</a>

                            <a class="btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Register">Register</a>
                        }

                      

                    </div>


                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Blog.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Blog.Web/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{

	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script>
		toastr.success('@TempData["Success"]')


	</script>

}
@if (TempData["Error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script>
		toastr.error('@TempData["Error"]')


	</script>
}

Blog.Web/Views/Shared/_noitfication.cshtml
@if (TempData["Success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script>
		toastr.success('@TempData["Success"]')


	</script>
}

@if (TempData["Error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script>
		toastr.success('@TempData["Error"]')


	</script>
}